### PR TITLE
fix(index): escape invalid characters

### LINKED ISSUE #42: Syntax error with special whitespace characters
I was trying to load a text file that was written with Google Docs.  It had issues like the character for " was the special “.

But that was not my issue.
It turns out that a special whitespace character was put in the file.  I used String.charCodeAt to find out the whitespace was of code: 8232 or 

U+2028 | line separator

I replaced all these characters and the raw-loader now works.
I'm filing this issue because I think that there needs to be some pre-processing to replace or correctly JSON stringify these characters.

### PR DESCRIPTION
**Pull request by joeheyming**
### `Notable Changes`

If your raw text has a string with Line separator or Paragraph separator,
they need to be handled outside of JSON.stringify:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Issue_with_plain_JSON.stringify_for_use_as_JavaScript

The fix here is to replace those characters as directed in the MDN article above.

I also changed the formatting from tabs to 2 spaces :-p

### `Issues`

- Fixes #42

### CODE REVIEW

**Comment by joeheyming** [comment]
This is related to Issue #43

**Comment by joeheyming** [comment]
This CI failure has nothing to do with my changes

**Comment by michael-ciniawsky** [comment]
`raw-loader@beta` should contain these changes, but we could/should backport them

File: index.js [hunk 1]
```diff
@@ -1,9 +1,14 @@
...
+  Author Tobias Koppers @sokra
 */
 module.exports = function(content) {
-	this.cacheable && this.cacheable();
-	this.value = content;
-	return "module.exports = " + JSON.stringify(content);
+  this.cacheable && this.cacheable();
+  this.value = content;
+
+  var stringified = JSON.stringify(content)
```
Comment (michael-ciniawsky) [inline index.js]: `var stringified = ...` => `content = ...` and maybe rename `content` to `json`please :)

File: index.js [hunk 2]
```diff
@@ -1,9 +1,14 @@
...
+  .replace(/\u2028/g, '\\u2028')
```
Comment (michael-ciniawsky) [inline index.js]: indent chained methods with 2 spaces please

```js
json = ...
  .method()
```

File: index.js (hunk 1 above)
Comment (joeheyming) [reply index.js]: the content is the raw text of the file.  It's not json

Comment (michael-ciniawsky) [reply index.js]: Yep, agreed `src` as argument and `var json = JSON.stringify(src)` is better :)

Comment (joeheyming) [reply index.js]: fixed

File: index.js [hunk 3]
```diff
@@ -1,9 +1,14 @@
...
-	Author Tobias Koppers @sokra
+  MIT License http://www.opensource.org/licenses/mit-license.php
+  Author Tobias Koppers @sokra
 */
-module.exports = function(content) {
-	this.cacheable && this.cacheable();
-	this.value = content;
-	return "module.exports = " + JSON.stringify(content);
+module.exports = function(source) {
+  this.cacheable && this.cacheable();
```
Comment (d3viant0ne) [inline index.js]: We don't support webpack 1.x. Cachable can be removed at this point

Comment (joeheyming) [reply index.js]: Ok

File: index.js [hunk 4]
```diff
@@ -1,9 +1,13 @@
...
-	this.value = content;
-	return "module.exports = " + JSON.stringify(content);
+module.exports = function(source) {
+  this.value = source;
+
+  var json = JSON.stringify(source)
+    .replace(/\u2028/g, '\\u2028')
+    .replace(/\u2029/g, '\\u2029');
+
+  return "module.exports = " + json;
```
Comment (stevemao) [inline index.js]: why not just `return "module.exports = " + '"' + source + '"'?

Comment (stevemao) [reply index.js]: Yeah I know. But why converting to json is better than wrapping the string with `"`?

Comment (joeheyming) [reply index.js]: Really, it's a matter of choice.  I've been used to using json stringify for things like this where code gets evaluated.  But yeah, you are right, it is the same.
